version: '3'

services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  nginx-ssl:
    ports:
      - "443:443"
    volumes:
      - ./default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/server.crt:/etc/server.crt:ro
      - ./ssl/server.key:/etc/server.key:ro

  server:
    environment:
      CLIENT: "http://client.chat.com"

  server-ssl:
    environment:
      CLIENT: "https://client.chat.com"